dist: xenial
language: node_js
cache: yarn
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - yarn ganache-cli -q &
  - yarn migrate
after_script:
  - greenkeeper-lockfile-upload
